import { ApiProperty } from '@nestjs/swagger';
import { IsBoolean, IsOptional, IsString } from 'class-validator';

export class UserResponseDto {
	@ApiProperty({
		example: '6760766a38d223a1a94b335d',
		description: 'Unique ID of the user generated by MongoDB',
	})
	_id: string;

	@ApiProperty({
		example: 'John',
		description: 'First name of the user',
	})
	firstName: string;

	@ApiProperty({
		example: 'Doe',
		description: 'Last name of the user',
	})
	lastName: string;

	@ApiProperty({
		example: '12345678901',
		description: 'CPF (tax identification number) of the user',
	})
	cpf: string;

	@ApiProperty({
		example: 'johndoe@test.com',
		description: 'User email',
	})
	email: string;

	@ApiProperty({
		example: 'Dermatologist',
		description: 'Profession of the user',
	})
	profession: string;

	@ApiProperty({
		example: ['Hair Transplant'],
		description: 'List of user specializations',
		type: [String],
	})
	specialization: string[];

	@ApiProperty({
		example: 'Available',
		description: 'Availability status of the user',
	})
	availabilityStatus: string;

	@ApiProperty({
		example: '3 years',
		description: 'Professional experience of the user',
	})
	professionalExperience: string;

	@ApiProperty({
		example: true || false,
		description:
			'Flag that identifies whether the user will be created as a clinic admin',
	})
	@IsOptional()
	@IsBoolean()
	isAdmin?: boolean;

	@ApiProperty({
		example: '',
		description:
			'Identifies the clinic for which the administrador user will be creatted',
	})
	@IsOptional()
	@IsString()
	clinicId: string;

	@ApiProperty({
		example: '2024-12-16T18:50:18.436Z',
		description: 'Date when the user record was created',
		type: String,
	})
	createdAt: string;

	@ApiProperty({
		example: '2024-12-16T18:50:18.436Z',
		description: 'Date when the user record was last updated',
		type: String,
	})
	updatedAt: string;

	@ApiProperty({
		example: 0,
		description: 'Version of the document in MongoDB',
	})
	__v: number;
}
