services:
  redis:  
    container_name: 'redis'
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
    command: /opt/bitnami/scripts/redis/run.sh
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
      