import { ApiProperty } from '@nestjs/swagger';
import { StatusEnum } from '../../common/enums/status.enum';

export class OpportunityResponseDto {
	@ApiProperty({
		description: 'Opportunity Title',
		example: 'Vacancy for hair transplant assistant',
	})
	title: string;

	@ApiProperty({
		description: 'Opportunity description',
		example: 'Opportunity to assist in hair transplant surgeries',
	})
	description: string;

	@ApiProperty({
		description: 'Opportunity location',
		example: '7th Avenue, New York',
	})
	location: string;

	@ApiProperty({
		description: 'Opportunity salary',
		example: 1400,
	})
	salary: number;

	@ApiProperty({
		description: 'Opportunity status',
		example: 'OPEN',
	})
	status: StatusEnum;

	@ApiProperty({
		description: 'Clinic responsible for the opportunity',
		example: 'Generic Clinic Name',
	})
	clinicName: string;

	@ApiProperty({
		description: 'Array of applicants for the opportunity',
		example: ['_id', '_id', '_id'],
	})
	applicants?: string[];

	@ApiProperty({
		example: '6760766a38d223a1a94b335d',
		description: 'Unique ID of the user generated by MongoDB',
	})
	_id?: string;

	@ApiProperty({
		example: '2024-12-16T18:50:18.436Z',
		description: 'Date when the user record was created',
		type: String,
	})
	createdAt?: Date;

	@ApiProperty({
		example: '2024-12-16T18:50:18.436Z',
		description: 'Date when the user record was last updated',
		type: String,
	})
	updatedAt?: Date;

	@ApiProperty({
		example: 0,
		description: 'Version of the document in MongoDB',
	})
	__v?: 0;
}
