import { ApiProperty } from '@nestjs/swagger';

export class ApplicationResponseDto {
	@ApiProperty({
		example: '6760766a38d223a1a94b335d',
		description: 'Unique ID of the user generated by MongoDB',
		type: String,
	})
	_id?: string;

	@ApiProperty({
		example: '67ba145c48ea4e5cdf5b5a0e',
		description: 'Opportunity ID',
	})
	opportunityId: string;

	@ApiProperty({
		example: '67bcbbdb1477995f877ff4d1',
		description: 'User ID',
	})
	userIds: string[];

	@ApiProperty({
		example: '2024-12-16T18:50:18.436Z',
		description: 'Date when the user record was created',
		type: String,
	})
	createdAt?: string;

	@ApiProperty({
		example: '2024-12-16T18:50:18.436Z',
		description: 'Date when the user record was last updated',
		type: String,
	})
	updatedAt?: string;

	@ApiProperty({
		example: 0,
		description: 'Version of the document in MongoDB',
	})
	__v?: number;
}
