import { ApiProperty } from '@nestjs/swagger';

export class ClinicResponseDtoSwagger {
		@ApiProperty({
			example: '6760766a38d223a1a94b335d',
			description: 'Unique ID of the user generated by MongoDB',
			type: String,
		})
		_id: string;

		@ApiProperty({
			example: 'Generic Clinic Name',
			description: 'Clinic Name',
			type: String,
		})
		clinicName: string;

		@ApiProperty({
			example: 'Los Angeles',
			description: 'Clinic address',
			type: String,
		})
		address: string;

		@ApiProperty({
			example: '551112341234',
			description: 'Clinic contact',
			type: String,
		})
		contact: string;

		@ApiProperty({
			example: 'Instagram',
			description: 'Clinic social network',
			type: String,
		})
		socialNetworks: string;

		@ApiProperty({
			example: 'Hair Transplant',
			description: 'Clinic specialization',
			type: String,
		})
		specializations: string;

		@ApiProperty({
			example: 'Generic corporate name',
			description: 'Corporate name',
			type: String,
		})
		corporateName: string;

		@ApiProperty({
			example: '12345678912345',
			description: 'Clinic CNPJ',
			type: String,
		})
		cnpj: string;

		@ApiProperty({
			example: 7,
			description: 'Number of days worked',
			type: Number,
		})
		openingDays: number;

		@ApiProperty({
			example: 'John Doe',
			description: 'Technically responsible person',
			type: String,
		})
		technicalManager: string;

		@ApiProperty({
			example: '2024-12-16T18:50:18.436Z',
			description: 'Date when the user record was created',
			type: String,
		})
		createdAt: string;

		@ApiProperty({
			example: '2024-12-16T18:50:18.436Z',
			description: 'Date when the user record was last updated',
			type: String,
		})
		updatedAt: string;

		@ApiProperty({
			example: 0,
			description: 'Version of the document in MongoDB',
		})
		__v: number;
	}
