import { ApiProperty } from '@nestjs/swagger';

export class ResponseUserDto {
	@ApiProperty({
		example: '6760766a38d223a1a94b335d',
		description: 'Unique ID of the user generated by MongoDB',
	})
	_id: string;

	@ApiProperty({
		example: 'John',
		description: 'First name of the user',
	})
	firstName: string;

	@ApiProperty({
		example: 'Doe',
		description: 'Last name of the user',
	})
	lastName: string;

	@ApiProperty({
		example: '12345678901',
		description: 'CPF (tax identification number) of the user',
	})
	cpf: string;

	@ApiProperty({
		example: 'Dermatologist',
		description: 'Profession of the user',
	})
	profession: string;

	@ApiProperty({
		example: ['Hair Transplant'],
		description: 'List of user specializations',
		type: [String],
	})
	specialization: string[];

	@ApiProperty({
		example: 'Available',
		description: 'Availability status of the user',
	})
	availabilityStatus: string;

	@ApiProperty({
		example: '3 years',
		description: 'Professional experience of the user',
	})
	professionalExperience: string;

	@ApiProperty({
		example: 'www.teste.com.br',
		description:
			'User professional portfolio URL or document (Upload coming soon)',
	})
	portfolio: string;

	@ApiProperty({
		example: '2024-12-16T18:50:18.436Z',
		description: 'Date when the user record was created',
		type: String,
	})
	createdAt: string;

	@ApiProperty({
		example: '2024-12-16T18:50:18.436Z',
		description: 'Date when the user record was last updated',
		type: String,
	})
	updatedAt: string;

	@ApiProperty({
		example: 0,
		description: 'Version of the document in MongoDB',
	})
	__v: number;
}
